data_dir: "data"
train_clean_path: "${dataset.data_dir}/train/clean"
train_noisy_path: "${dataset.data_dir}/train/noisy"
test_noisy_path: "${dataset.data_dir}/test/noisy_testset_wav"
test_clean_path: "${dataset.data_dir}/test/clean_testset_wav"

batch_size: 4
num_workers: 7
